version: 2

linters:
  disable:
    - wrapcheck
    - contextcheck
    - exhaustive
    - protogetter
  presets:
    - bugs
    - error
    - unused

run:
  tests: false

issues:
  exclude-dirs:
    - .github
